# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gmehta3/enforcer
  tag: "2"
  pullPolicy: Always

# Persistence sections details with persistence of trivy cache.
# This should speed up the initial cache.
persistence:
  enabled: true 
  # Override for non default storage class 
  storageProvider: "longhorn"
  storageAllocation: 10Gi
