# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gmehta3/enforcer
  tag: latest
  pullPolicy: Always

# Persistence sections details with persistence of trivy cache.
# This should speed up the initial cache.
persistence:
  enabled: true 
  storageProvider: ""
  storageAllocation: 10Gi