{{- if and .Values.persistence.enabled .Values.persistence.storageProvider }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.storageAllocation | default "10Gi" }}
  storageClassName: {{ .Values.persistence.storageProvider }}
{{ end -}}