apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-webhook
  labels:
    app: {{ .Chart.Name }}-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-webhook
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-webhook
    spec:
      containers:
        - name: {{ .Chart.Name }}-webhook
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.client.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          command:
            - "enforcer"
          args:
            - "-tls-cert-file"
            - "/certs/cert.pem"
            - "-tls-key-file"
            - "/certs/key.pem"
            - "-port"
            - "443"
            - "-ignorefile"
            - "/mnt/trivyignore"
          volumeMounts:
            - name: webhook-certs
              mountPath: /certs
              readOnly: true
            - name: ignorelist
              mountPath: /mnt
      volumes:
        - name: webhook-certs
          secret:
            secretName: enforcer-certs
        - name: ignorelist
          configMap:
            name: ignorelist
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-webhook
  labels:
    app: {{ .Chart.Name }}-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: {{ .Chart.Name }}-webhook
