apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "enforcer"
            - "-severity"
            - "CRITICAL"
            - "-tls-cert-file"
            - "/certs/cert.pem"
            - "-tls-key-file"
            - "/certs/key.pem"
            - "-port"
            - "443"
          volumeMounts:
            - name: webhook-certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: enforcer-certs
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: {{ .Release.Name }}
